#!/bin/bash

source "$(dirname "$0")/_common.sh"
source /usr/share/yunohost/helpers

ynh_script_progression --message="Updating the nginx configuration..." --weight=5
ynh_change_url_nginx_config

nginx -t && systemctl reload nginx

ynh_script_progression --message="Change of URL completed." --last
