#!/bin/bash
# Auteur : Patrick Ritaine

source "$(dirname "$0")/_common.sh"
source /usr/share/yunohost/helpers

ynh_script_progression --message="Stopping and removing the service..." --weight=10

if yunohost service status "$app" >/dev/null 2>&1; then
    yunohost service remove "$app"
fi

systemctl stop "$app" 2>/dev/null || true
systemctl disable "$app" 2>/dev/null || true

ynh_script_progression --message="Removing the systemd configuration..." --weight=5
ynh_remove_systemd_config


ynh_script_progression --message="Removal completed." --last
