#!/bin/bash
# Auteur : Patrick Ritaine
set -eu

CONF=/etc/nginx/conf.d/yunohost_api.conf.inc

if [ -f "$CONF" ] && ! grep -q 'allow 127.0.0.1;' "$CONF"; then
    sed -i '/location \/yunohost\/portalapi\/ {/a\
\    allow 127.0.0.1;\
\    deny all;' "$CONF"
    nginx -t && systemctl reload nginx
fi
