
packaging_format = 2

id = "wappos_admin"
name = "Wappos Admin"
description.en = "Wappos administration portal (MVP) — user management, consuming the Wappos API's Admin connector instead of the native YunoHost WebAdmin"
description.fr = "Portail d'administration Wappos (MVP) — gestion des utilisateurs, consommant le connecteur Admin de l'API Wappos plutôt que le WebAdmin natif YunoHost"

version = "0.3.9~ynh76"

maintainers = ["byrtn"]

[upstream]
license = "AGPL-3.0-or-later"

[integration]
yunohost = ">= 12.1.0"
helpers_version = "2.0"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = "not_relevant"
sso = false

disk = "100M"
ram.build = "100M"
ram.runtime = "100M"

[resources]
    [resources.system_user]

    [resources.install_dir]
    dir = "/opt/yunohost/__APP__"

    [resources.ports]
    main.default = 9500

    [resources.apt]
    packages = "python3-venv, python3-pip"
