#!/bin/bash
set -eu

python3 /usr/local/lib/wappos_sso_bypass/regen_bypass_conf.py

mkdir -p /etc/nginx/conf.d/default.d
cat > /etc/nginx/conf.d/default.d/redirect_to_admin.conf <<'NGINX_EOF'
location / {
    if ($scheme = http) {
        return 308 https://$host$request_uri;
    }
    return 302 https://$host/wappos-portal/;
}
NGINX_EOF

cat > /etc/nginx/conf.d/default.d/wappos_sso_assets.conf <<'NGINX_EOF'
include /etc/nginx/conf.d/yunohost_sso.conf.inc;
NGINX_EOF

nginx -t && systemctl reload nginx
